### ISSUE TITLE
[Need review] Subscribe + send email flow

### ISSUE THREAD

**Issue by khaitruong922** [RMIT-FinTech-Club/ClubWeb#11]
![image](https://user-images.githubusercontent.com/56820749/144866983-edbb2f7c-d2d0-45c7-9eed-f403faad1fd8.png)

Since we already have all the registered user in Firebase, we can fetch all the emails and filtered by subscribing status (can be stored in Firestore) instead of managing the emails in Strapi.

When a post is made, Strapi will send email to all the subscribing emails fetched from Firebase.

**Comment by khaitruong922** [comment]
@chungquantin @hungthezorba Please review this architecture so that I can start working on this feature ASAP. Thanks!

**Comment by hungthezorba** [comment]
LGTM. I think it is a fine architecture

**Comment by khaitruong922** [comment]
![image](https://user-images.githubusercontent.com/56820749/145168241-64817fce-fec7-4bdc-b79b-545e70d162cb.png)

New architecture:
- Use webhook handler server as an intermediate to handle sending email when a post is published (https://github.com/RMIT-FinTech-Club/cms-webhook-handler)

Why:
- Cloud function is not in free plan.
- SendGrid integration with Strapi does not work due to many issues with the SMTP

Progress:
- Finish sending email function.
- Publishing post triggers webhook and call API on handler server.

TODO:
- Fetch all subscribing emails from Firestore.
- Email template (need discussion on design)
- Security on handler server (only Strapi server can trigger handler)

![image](https://user-images.githubusercontent.com/56820749/145169644-c018b304-074b-41ff-9949-d3bac17e24b3.png)

![image](https://user-images.githubusercontent.com/56820749/145168960-caa170d5-0c40-4f7f-8b28-f2d4e682ef28.png)

**Comment by hungthezorba** [comment]
Webhook server is built from node?

**Comment by khaitruong922** [comment]
> Webhook server is built from node?

Yes, that's right.
